language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
# before_script:
# - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker build --rm -f Build.dockerfile -t pckzs/nrfsdk-gcc .
services:
  - docker
branches:
  only:
    - master
